languageCode = 'en-us'
theme = 'risotto'
title = 'danielunderwood.dev'

[params]

[params.theme]
palette = "custom"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
#title = "danielunderwood.dev"
#description = "My personal website"

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/danielunderwood"

[[params.socialLinks]]
icon = "fa fa-envelope"
title = "Email"
url = "mailto:hello@danielunderwood.dev"

[[params.socialLinks]]
icon = "fa fa-rss"
title = "RSS"
url = "/index.xml"

[menu]

#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10

  [[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/post/"

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = true
    style = "monokai"